#version 450

#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_EXT_shader_atomic_float2 : require
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer Q {float qState[];};
layout (binding = 0) readonly buffer Q_VEC2 {f16vec2 qStateVec2[];};
layout (binding = 1) readonly buffer K {float16_t kState[];};
layout (binding = 1) readonly buffer K_VEC2 {f16mat2x4 kStateVec2[];};
layout (binding = 2) buffer MASK {f16vec2 mState[];};
layout (binding = 2) buffer MASK_F16 {float16_t mState_f16[];};
layout (binding = 3) buffer P_FP32 {float matP_f32[];};
layout (binding = 3) buffer P_FP16 {float16_t matP_f16[];};
layout (binding = 4) buffer OUT_MAX {float out_max_f32[];};
layout (binding = 5) buffer GLOBAL_MAX_FP32 {float global_max_f32[];};

layout (push_constant) uniform parameter
{
  uint kvSeqLen;
  uint activationLength;
  uint qHead;
  uint kvHead;
  uint qkRatio;
  uint qkSubGroups;
  uint flag;
  uint kvStride;
  uint batchStrideQ;
  uint batchStrideK;
  uint batchStrideV;
  uint batchStrideM;
  uint batchStrideO;
  float softMaxScale;
} p;

layout (constant_id = 0) const uint GROUPSIZE = 32; // 3 = log2(8)
layout (constant_id = 1) const uint GQA_RATIO = 8; // 3 = log2(8)
layout (constant_id = 2) const uint HEAD_DIM = 128;
layout (constant_id = 3) const uint MTP = 2;
layout (constant_id = 4) const uint WARPSIZE = 16;
layout (constant_id = 5) const uint MAT_P_DIV = 1;

#define MAX_HEADS 8
#define N_TOKS (MTP + 1)

#define MAT_P_COUNT (DP / WARPSIZE)
#define MATP_REDUCE (GROUPSIZE / 2)
#define SUBGROUP_COUNT (GROUPSIZE / WARPSIZE)
#define SUBGROUP_DIVISION (SUBGROUP_COUNT / GQA_RATIO)

#define K_COUNT (WARPSIZE / 8)
#define O_COUNT ((GQA_RATIO + SUBGROUP_COUNT - 1) / SUBGROUP_COUNT)

shared float slm_pool_pv[N_TOKS * GQA_RATIO * GROUPSIZE];
shared float slm_pool_max_temp[GQA_RATIO];

void main() {
  const uint lane = gl_SubgroupInvocationID;
  const uint pWarpIdx = gl_WorkGroupID.x % MAT_P_DIV;
  const uint vWarpIdx = gl_WorkGroupID.x / MAT_P_DIV;
  const uint v = gl_WorkGroupID.y;
  const uint d = gl_WorkGroupID.z;
  const uint localLinearId = gl_SubgroupID;
  const uint hhq = localLinearId & 0x1;
  const uint vvq = localLinearId >> 1;
  const uint qDim = p.qHead * HEAD_DIM;
  const uint oDim = qDim;
  const uint kvDim = p.kvStride;
  const uint maskDim = p.kvSeqLen;
  const uint offsetBaseQ = (d * p.batchStrideQ + pWarpIdx * N_TOKS * qDim + vWarpIdx * HEAD_DIM * GQA_RATIO + hhq * WARPSIZE + lane);
  const uint offsetBaseK = (d * p.batchStrideK + (v * MATP_REDUCE + vvq * WARPSIZE) * kvDim + lane * kvDim + vWarpIdx * HEAD_DIM + hhq * K_COUNT * 8) / 8;
  const uint offsetOut = d * p.activationLength * p.qHead * p.kvSeqLen + v * MATP_REDUCE + pWarpIdx * N_TOKS * p.qHead * p.kvSeqLen + vWarpIdx * GQA_RATIO * p.kvSeqLen + localLinearId * O_COUNT * p.kvSeqLen + lane;
  const uint offsetMax = d * p.activationLength * p.qHead * p.kvSeqLen / MATP_REDUCE + v + pWarpIdx * N_TOKS * p.qHead * p.kvSeqLen / MATP_REDUCE + vWarpIdx * GQA_RATIO * p.kvSeqLen / MATP_REDUCE + localLinearId * O_COUNT * p.kvSeqLen / MATP_REDUCE;
  const uint offsetGlobalMax = d * p.activationLength * p.qHead + pWarpIdx * N_TOKS * p.qHead + vWarpIdx * GQA_RATIO + localLinearId * O_COUNT;
  const uint offsetSlmPv = (localLinearId * WARPSIZE + lane);
  const uint offsetSlmLoadPv = (localLinearId * O_COUNT * GROUPSIZE + lane);
  const uint offsetBaseM = d * p.batchStrideM + v * MATP_REDUCE + lane + pWarpIdx * N_TOKS * maskDim;
  const float16_t fp16SoftmaxScale = float16_t(p.softMaxScale);
  const float fp32Min = uintBitsToFloat(0xFEFFFFFF);
  f16mat2x4 matK[K_COUNT];
  float matQ[N_TOKS][GQA_RATIO];
  float fp32P[N_TOKS][GQA_RATIO];
  float fp32TempO[GROUPSIZE / WARPSIZE];
  float fp32O[O_COUNT][MATP_REDUCE / WARPSIZE];
  float maxOut[O_COUNT];
  float16_t mask[N_TOKS][MATP_REDUCE / WARPSIZE];

  [[unroll]] for (uint n = 0; n < N_TOKS; n++) {
    [[unroll]] for (uint i = 0; i < GQA_RATIO; i++) {
      fp32P[n][i] = 0.0f;
    }
  }

  [[unroll]] for (uint n = 0; n < N_TOKS; n++) {
    [[unroll]] for (uint i = 0; i < MATP_REDUCE / WARPSIZE; i++) {
      mask[n][i] = mState_f16[n * maskDim + i * WARPSIZE + offsetBaseM];
    }
  }

  const uint loopCount = HEAD_DIM / WARPSIZE / 2;
  [[unroll]] for (uint loop = 0; loop < loopCount; loop++) {
    [[unroll]] for (uint kd = 0; kd < K_COUNT; kd++) {
      matK[kd] = kStateVec2[offsetBaseK + loop * 2 * K_COUNT + kd];
    }

    [[unroll]] for (uint n = 0; n < N_TOKS; n++) {
      [[unroll]] for (uint qd = 0; qd < GQA_RATIO; qd++) {
        matQ[n][qd] = qState[offsetBaseQ + n * qDim + loop * 2 * WARPSIZE + qd * HEAD_DIM];
      }
    }

    [[unroll]] for (uint n = 0; n < N_TOKS; n++) {
      [[unroll]] for (uint nn = 0; nn < GQA_RATIO; nn++) {
        [[unroll]] for (uint kk = 0; kk < K_COUNT; kk++) {
          fp32P[n][nn] = fma(float(matK[kk][0].x), subgroupBroadcast(matQ[n][nn], 8 * kk + 0), fp32P[n][nn]);
          fp32P[n][nn] = fma(float(matK[kk][0].y), subgroupBroadcast(matQ[n][nn], 8 * kk + 1), fp32P[n][nn]);
          fp32P[n][nn] = fma(float(matK[kk][0].z), subgroupBroadcast(matQ[n][nn], 8 * kk + 2), fp32P[n][nn]);
          fp32P[n][nn] = fma(float(matK[kk][0].w), subgroupBroadcast(matQ[n][nn], 8 * kk + 3), fp32P[n][nn]);
          fp32P[n][nn] = fma(float(matK[kk][1].x), subgroupBroadcast(matQ[n][nn], 8 * kk + 4), fp32P[n][nn]);
          fp32P[n][nn] = fma(float(matK[kk][1].y), subgroupBroadcast(matQ[n][nn], 8 * kk + 5), fp32P[n][nn]);
          fp32P[n][nn] = fma(float(matK[kk][1].z), subgroupBroadcast(matQ[n][nn], 8 * kk + 6), fp32P[n][nn]);
          fp32P[n][nn] = fma(float(matK[kk][1].w), subgroupBroadcast(matQ[n][nn], 8 * kk + 7), fp32P[n][nn]);
        }
      }
    }
  }

  [[unroll]] for (uint n = 0; n < N_TOKS; n++) {
    [[unroll]] for (uint nn = 0; nn < GQA_RATIO; nn++) {
      fp32P[n][nn] = fp32P[n][nn] * p.softMaxScale;
    }
  }

  [[unroll]] for (uint n = 0; n < N_TOKS; n++) {
    [[unroll]] for (uint pd = 0; pd < GQA_RATIO; pd++) {
      slm_pool_pv[offsetSlmPv + pd * GROUPSIZE + n * GQA_RATIO * GROUPSIZE] = fp32P[n][pd];
    }
  }

  barrier();

  if (O_COUNT * localLinearId < GQA_RATIO) {
    [[unroll]] for (uint n = 0; n < N_TOKS; n++) {
      float maskFp32[MATP_REDUCE / WARPSIZE];
      [[unroll]] for (uint i = 0; i < MATP_REDUCE / WARPSIZE; i++) {
        maskFp32[i] = float(mask[n][i]);
      }
      [[unroll]] for (uint oc = 0; oc < O_COUNT; oc++) {
        [[unroll]] for (uint os = 0; os < GROUPSIZE / WARPSIZE; os++) {
          fp32TempO[os] = slm_pool_pv[offsetSlmLoadPv + n * GQA_RATIO * GROUPSIZE + os * WARPSIZE + oc * GROUPSIZE];
        }

        [[unroll]] for (uint os = 0; os < MATP_REDUCE / WARPSIZE; os++) {
          fp32O[oc][os] = fp32TempO[2 * os] + fp32TempO[2 * os + 1];
        }

        [[unroll]] for (uint os = 0; os < MATP_REDUCE / WARPSIZE; os++) {
          fp32O[oc][os] = fp32O[oc][os] + maskFp32[os];
        }

        float maxTemp = fp32Min;
        [[unroll]] for (uint os = 0; os < MATP_REDUCE / WARPSIZE; os++) {
          maxTemp = max(maxTemp, fp32O[oc][os]);
        }
        maxOut[oc] = subgroupMax(maxTemp);
        [[unroll]] for (uint os = 0; os < MATP_REDUCE / WARPSIZE; os++) {
          fp32O[oc][os] = exp(fp32O[oc][os] - maxOut[oc]);
        }
      }

      [[unroll]] for (uint oc = 0; oc < O_COUNT; oc++) {
        [[unroll]] for (uint os = 0; os < MATP_REDUCE / WARPSIZE; os++) {
          matP_f16[offsetOut + n * p.qHead * p.kvSeqLen + oc * p.kvSeqLen + os * WARPSIZE] = float16_t(fp32O[oc][os]);
        }
        if (lane == 0) {
          out_max_f32[offsetMax + n * p.qHead * p.kvSeqLen / MATP_REDUCE + oc * p.kvSeqLen / MATP_REDUCE] = maxOut[oc];
          atomicMax(global_max_f32[offsetGlobalMax + oc + n * p.qHead], maxOut[oc]);
        }
      }
    }
  }
}
